/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaAdmin;

import classes_de_conexao.Conexao;

import Classes.Loja;
import classes_de_conexao.Conexao;
import loginandcadastro.Login;
import loginandcadastro.LoginAndCadastro;
import classes_de_conexao.Conexao;
import java.awt.Image;
import java.awt.List;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telaLojista.TelaDoLojista;

/**
 *
 * @author Ramon Souza
 */
public class ListarProdutosCadastrados extends javax.swing.JFrame {

    private boolean verify;

    public boolean isVerify() {
        return verify;
    }

    public void setVerify(boolean verify) {
        this.verify = verify;
    }
    
    
    /**
     * Creates new form ListarProdutosCadastrados
     */
    public ListarProdutosCadastrados() {
        initComponents();
    }
    
    public ListarProdutosCadastrados(boolean verify) {
        initComponents();
        this.verify = verify;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        right = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblFoto3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfNomeProduto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfIdProduto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfPrecoDoProduto = new javax.swing.JTextField();
        listarProdutoBtnProximo = new javax.swing.JButton();
        listarProdutoBtnAnterior = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tfTempoDePreparo = new javax.swing.JTextField();
        btnRemoverProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(234, 29, 44));
        Left.setPreferredSize(new java.awt.Dimension(400, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramon Souza\\Documents\\NetBeansProjects\\LoginAndCadastro\\src\\Icon\\logo250x250-removebg-preview.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setText("copyright © RSFOOD Todos os direitos reservados");

        voltar.setForeground(new java.awt.Color(234, 29, 44));
        voltar.setText("Voltar");
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltar))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 340, 620);

        right.setMinimumSize(new java.awt.Dimension(500, 600));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 500));

        lblFoto3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ramon Souza\\Downloads\\camera.png")); // NOI18N
        lblFoto3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel16.setText("Nome do Produto:");

        tfDescricao.setEditable(false);

        jLabel17.setText("Descrição do Produto:");

        tfNomeProduto.setEditable(false);

        jLabel18.setText("id do Produto:");

        tfIdProduto.setEditable(false);

        jLabel19.setText("Preço do Produto:");

        tfPrecoDoProduto.setEditable(false);

        listarProdutoBtnProximo.setText("❯");
        listarProdutoBtnProximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarProdutoBtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutoBtnProximoActionPerformed(evt);
            }
        });

        listarProdutoBtnAnterior.setText("❮");
        listarProdutoBtnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel21.setText("Tempo de Preparo:");

        tfTempoDePreparo.setEditable(false);

        btnRemoverProd.setBackground(new java.awt.Color(234, 29, 44));
        btnRemoverProd.setText("Remover Produto");
        btnRemoverProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoverProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(tfPrecoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfIdProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfTempoDePreparo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfDescricao)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(101, 101, 101))
                        .addComponent(tfNomeProduto))
                    .addComponent(jLabel17))
                .addGap(58, 58, 58))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listarProdutoBtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnRemoverProd, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listarProdutoBtnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTempoDePreparo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecoDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listarProdutoBtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listarProdutoBtnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnRemoverProd)))
                .addGap(63, 63, 63))
        );

        jPanel9.add(jPanel10);

        jScrollPane4.setViewportView(jPanel9);

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(right);
        right.setBounds(340, 0, 560, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        if (verify == false) {
            telaDoAdministrador adminFrame = new telaDoAdministrador();
            adminFrame.setVisible(true);
            adminFrame.pack();
            adminFrame.setLocationRelativeTo(null); // para abrir sempre no centro da tela
            this.dispose();

            System.out.println("eh adm");

        } else if (verify == true) {

            System.out.println("Eh lojista");

            Login lojistaFrame = new Login();
            lojistaFrame.setVisible(true);
            lojistaFrame.pack();
            lojistaFrame.setLocationRelativeTo(null); // Para abrir sempre no centro da tela
            this.dispose();
        }
    }//GEN-LAST:event_voltarActionPerformed

    private void listarProdutoBtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutoBtnProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarProdutoBtnProximoActionPerformed

    private void btnRemoverProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdActionPerformed
        // TODO add your handling code here:
        removerProduto();
    }//GEN-LAST:event_btnRemoverProdActionPerformed

    
    public void removerProduto() {
        
        
        if (tfIdProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe um Id por favor");
        } else {
            try {

                Connection con = Conexao.faz_conexao();

                // verificação se o ID existe
                String verificaSql = "SELECT id_produto FROM dados_produtos WHERE id_produto = ?";
                PreparedStatement verificaStmt = con.prepareStatement(verificaSql);
                verificaStmt.setString(1, tfIdProduto.getText());
                ResultSet rs = verificaStmt.executeQuery();

                // verificação se o ID existe no banco de dados
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(null, "O iD informado não existe ou já foi excluido.");
                } else {
                    // se o ID existe, ele pede a confirmação para excluir
                    int confirmacao = JOptionPane.showConfirmDialog(
                            null,
                            "Esta ação não pode ser desfeita. Quer continuar?",
                            "Confirmação de Exclusão",
                            JOptionPane.YES_NO_OPTION
                    );

                    if (confirmacao == JOptionPane.YES_OPTION) {
                        // executa o DELETE
                        String sql = "DELETE FROM dados_produtos WHERE id_produto = ?";
                        PreparedStatement stmt = con.prepareStatement(sql);
                        stmt.setString(1, tfIdProduto.getText());
                        stmt.execute();

                        JOptionPane.showMessageDialog(null, "Loja removido com Sucesso!");
                        tfIdProduto.setText("");
                        tfTempoDePreparo.setText("");
                        tfNomeProduto.setText("");
                        tfPrecoDoProduto.setText("");
                        tfDescricao.setText("");
                        
                        lblFoto3.setIcon(new ImageIcon(RemoverLojas.class.getResource("/icon/camera.png")));

                        stmt.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "A remoção foi cancelada.");
                    }
                }

                verificaStmt.close();
                rs.close();
                con.close();

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProdutosCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProdutosCadastrados().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JButton btnRemoverProd;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JButton listarProdutoBtnAnterior;
    private javax.swing.JButton listarProdutoBtnProximo;
    private javax.swing.JPanel right;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfIdProduto;
    private javax.swing.JTextField tfNomeProduto;
    private javax.swing.JTextField tfPrecoDoProduto;
    private javax.swing.JTextField tfTempoDePreparo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblFoto3() {
        return lblFoto3;
    }

    public void setLblFoto3(JLabel lblFoto) {
        this.lblFoto3 = lblFoto;
    }

    public javax.swing.JTextField getTfDescricao() {
        return tfDescricao;
    }

    public void setTfDescricao(javax.swing.JTextField tfDescricao) {
        this.tfDescricao = tfDescricao;
    }

    public javax.swing.JTextField getTfIdProduto() {
        return tfIdProduto;
    }

    public void setTfIdProduto(javax.swing.JTextField tfIdProduto) {
        this.tfIdProduto = tfIdProduto;
    }

    public javax.swing.JTextField getTfNomeProduto() {
        return tfNomeProduto;
    }

    public void setTfNomeProduto(javax.swing.JTextField tfNomeProduto) {
        this.tfNomeProduto = tfNomeProduto;
    }

    public javax.swing.JTextField getTfPrecoDoProduto() {
        return tfPrecoDoProduto;
    }

    public void setTfPrecoDoProduto(javax.swing.JTextField tfPrecoDoProduto) {
        this.tfPrecoDoProduto = tfPrecoDoProduto;
    }

    public javax.swing.JTextField getTfTempoDePreparo() {
        return tfTempoDePreparo;
    }

    public void setTfTempoDePreparo(javax.swing.JTextField tfTempoDePreparo) {
        this.tfTempoDePreparo = tfTempoDePreparo;
    }

    public javax.swing.JButton getListarProdutoBtnAnterior() {
        return listarProdutoBtnAnterior;
    }

    public void setListarProdutoBtnAnterior(javax.swing.JButton listarProdutoBtnAnterior) {
        this.listarProdutoBtnAnterior = listarProdutoBtnAnterior;
    }

    public javax.swing.JButton getListarProdutoBtnProximo() {
        return listarProdutoBtnProximo;
    }

    public void setListarProdutoBtnProximo(javax.swing.JButton listarProdutoBtnProximo) {
        this.listarProdutoBtnProximo = listarProdutoBtnProximo;
    }

}
